import React, { useState } from 'react';
import { Alert, Button, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList, Priority } from '../types';
import { useTasks } from '../context/TaskContext';

type Props = NativeStackScreenProps<RootStackParamList, 'EditTask'>;
export default function EditTaskScreen({ route, navigation }: Props) { const { getTask, updateTask } = useTasks(); const task=getTask(route.params.taskId); const [title,setTitle]=useState(task?.title||''); const [subject,setSubject]=useState(task?.subject||''); const [description,setDescription]=useState(task?.description||''); const [dueDate,setDueDate]=useState(task?.dueDate||''); const [priority,setPriority]=useState<Priority>(task?.priority||'Medium'); const [error,setError]=useState(''); if(!task)return <Text>Task not found.</Text>; const save=()=>{if(title.trim().length<3||!subject.trim()||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(dueDate)){setError('Please provide a valid title, subject, and due date (YYYY-MM-DD).');return;} updateTask(task.id,{title:title.trim(),subject:subject.trim(),description:description.trim(),dueDate,priority}); Alert.alert('Updated','Task updated successfully.');navigation.goBack();}; return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><Text style={styles.heading}>Edit Task</Text><Text style={styles.label}>Title</Text><TextInput value={title} onChangeText={setTitle} style={styles.input}/><Text style={styles.label}>Subject</Text><TextInput value={subject} onChangeText={setSubject} style={styles.input}/><Text style={styles.label}>Description</Text><TextInput value={description} onChangeText={setDescription} multiline style={[styles.input,{height:100,textAlignVertical:'top'}]}/><Text style={styles.label}>Due Date</Text><TextInput value={dueDate} onChangeText={setDueDate} placeholder="YYYY-MM-DD" style={styles.input}/><Text style={styles.label}>Priority: {priority}</Text><View style={styles.row}>{(['Low','Medium','High'] as Priority[]).map(p=><Button key={p} title={p} onPress={()=>setPriority(p)}/>)}</View>{error?<Text style={styles.error}>{error}</Text>:null}<Button title="Save Changes" onPress={save}/></ScrollView></SafeAreaView>; }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8fafc'},container:{padding:20,maxWidth:700,width:'100%',alignSelf:'center'},heading:{fontSize:28,fontWeight:'800',marginBottom:10},label:{fontWeight:'700',marginTop:15,marginBottom:7},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#cbd5e1',borderRadius:12,padding:12},row:{flexDirection:'row',justifyContent:'space-between',marginBottom:15},error:{color:'#dc2626',marginBottom:15}});
