import React from 'react';
import { Alert, Button, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '../types';
import { useTasks } from '../context/TaskContext';

type Props = NativeStackScreenProps<RootStackParamList, 'TaskDetails'>;
export default function TaskDetailsScreen({ route, navigation }: Props) { const { getTask, deleteTask, toggleTask } = useTasks(); const task = getTask(route.params.taskId); if (!task) return <SafeAreaView style={styles.safe}><Text>Task not found.</Text></SafeAreaView>; return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><View style={styles.header}><Text style={styles.title}>{task.title}</Text><View style={styles.badge}><Text>{task.priority} Priority</Text></View></View><Text style={styles.subject}>{task.subject}</Text><Text style={styles.label}>Description</Text><Text style={styles.description}>{task.description || 'No description provided.'}</Text><Text style={styles.label}>Due Date</Text><Text style={styles.value}>{task.dueDate}</Text><Text style={styles.label}>Status</Text><Text style={[styles.value, { color: task.status === 'Completed' ? '#16a34a' : '#d97706' }]}>{task.status}</Text><View style={styles.actions}><Button title={task.status === 'Completed' ? 'Mark Pending' : 'Mark Completed'} onPress={() => toggleTask(task.id)} /><Button title="Edit Task" onPress={() => navigation.navigate('EditTask', { taskId: task.id })} /><Button title="Delete Task" color="#dc2626" onPress={() => { Alert.alert('Delete Task','Delete this task?', [{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>{deleteTask(task.id);navigation.goBack();}}]); }} /></View></ScrollView></SafeAreaView>; }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8fafc'},container:{padding:20,maxWidth:700,width:'100%',alignSelf:'center'},header:{backgroundColor:'#fff',borderRadius:18,padding:18,borderWidth:1,borderColor:'#e2e8f0'},title:{fontSize:25,fontWeight:'800'},badge:{alignSelf:'flex-start',backgroundColor:'#e0e7ff',paddingHorizontal:10,paddingVertical:6,borderRadius:12,marginTop:10},subject:{color:'#2563eb',fontSize:15,fontWeight:'700',marginTop:14},label:{fontWeight:'800',marginTop:24,marginBottom:7,color:'#334155'},description:{backgroundColor:'#fff',padding:15,borderRadius:14,lineHeight:22,color:'#475569'},value:{fontSize:16,fontWeight:'600'},actions:{gap:12,marginTop:30}});
